### ISSUE TITLE
semantic versioning ?

### ISSUE THREAD

**Issue by ICA-uw** [HUSST-de/HUSST#16]
Wenn auch 3_00 jetzt erst mal fertig ist...
Martin hatte  mal semantic versioning ins Spiel gebracht: https://semver.org/
Wäre es auch für HUSST 3.0 (3.0.0) sinnvoll ?

**Comment by AMCON-Gerst** [comment]
Können wir gerne machen, wenn wir dann einen "Bugfix" machen, können wir den ja 3.00.1 nennen 🤔

**Comment by horst-p-w-neubauer** [comment]
Semantic Versioning ist am 10.02.2023 in Cloppenburg beschlossen und mit Version 3.2.0 implementiert worden.
