### ISSUE TITLE
Personaldaten Husst 3

### ISSUE THREAD

**Issue by AMCON-Gerst** [HUSST-de/HUSST#45]
In Husst 2 waren Personaldaten Bestandteil der Husst Versorgungsdaten.
In Husst 3 sind diese rausgeflogen, da keine Anwendung bekannt war, die diese nutzt.

Nun wurde herangetragen, dass diese Daten doch genutzt werden.

Idee:
* Eigenen XSDs um Tabellen für Personaldaten von den Tarifdaten zu trennen.

**Comment by horst-p-w-neubauer** [comment]
Das ist im Grunde eine gute Idee.
Sie läuft auf einen ersten Modularisierungsschritt hinaus, was die zentrale Idee für die Husst Daisy ist.
Die Herausforderung, die ich dabei sehe ist, dass wir uns zwischen diesen Alternativen entscheiden müssen
* einige allgemeine Datentypen doppelt definieren (Zeitraeume, Unternehmen, VersionStruktur, ..)
* die allgemeinen Datentypen in eine eigene .xsd ausgliedern
* in die HUSST_Personaldaten .xsd die Versorgungsdaten als namespace aufnehmen

Meine Präferenz liegt bei der letzten Alternative.
Wenn ich das richtig sehe, müssten die Personaldaten allerdings einen eigenen Root Datentyp definieren.
So etwas wie:
Husst3Personal_Type (das Gegenstück wäre der OePVTarifDB_Type in der Husst_Versorgungsdaten Struktur)

Ich bitte um Rückmeldung von den Kollegen, wo eure Präferenz liegt.

**Comment by horst-p-w-neubauer** [comment]
@Almex-OES, @AMCON-Gerst , @highQ-Gumbert, @ICA-uw:
Ich hätte gerne mindestens eine Rückmeldung von Almex, AMCON, highQ und ICA wie wir die allgemeinen Datentypen in die separate HUSST_Personaldaten.xsd integrieren wollen (siehe meinen obigen Kommentar),  würdet ihr vier das bitte für euer Unternehmen jeweils organisieren? Mein Ziel ist es, zum nächsten Husst-AG-Treffen am 14. März d.J. einen .xsd-Vorschlag vorzubereiten. Vielen Dank.

**Comment by highQ-Gumbert** [comment]
@horst-p-w-neubauer:
Wir bevorzugen Variante 2 (eigene XSD-Datei für die allgemeinen Datentypen). Variante 1 würden wir komplett ausschließen wollen.

**Comment by horst-p-w-neubauer** [comment]
> @horst-p-w-neubauer: Wir bevorzugen Variante 2 (eigene XSD-Datei für die allgemeinen Datentypen). Variante 1 würden wir komplett ausschließen wollen.

Vielen Dank für die Rückmeldung!

**Comment by ICA-uw** [comment]
Wir schließen Variante 1 auch aus und bevorzugen ebenfalls Variante 2.
Variante 3 ist nicht so sinnvoll, da die beiden Bereiche eher getrennt zu betrachten sind und wohl auch getrennt gepflegt werden.

**Comment by horst-p-w-neubauer** [comment]
> Wir schließen Variante 1 auch aus und bevorzugen ebenfalls Variante 2. Variante 3 ist nicht so sinnvoll, da die beiden Bereiche eher getrennt zu betrachten sind und wohl auch getrennt gepflegt werden.    

Vielen Dank für die Rückmeldung!

**Comment by AMCON-Gerst** [comment]
Variante 1 finden wir auch Schwachsinnig.

Für die Entscheidung, ob Varianten 2 oder 3 stellt sich die Frage, ob man eine große Versorgung erstellen möchte oder getrennte Versorgungen für Personal und Tarifdaten.

Wir würden eher getrennte Versorgungen bevorzugen, da die Daten in keinen direkten Zusammenhang stehen.
=> Variante 2

**Comment by horst-p-w-neubauer** [comment]
> Für die Entscheidung, ob Varianten 2 oder 3 stellt sich die Frage, ob man eine große Versorgung erstellen möchte oder getrennte Versorgungen für Personal und Tarifdaten.

@AMCON-Gerst 
Den Hinweis verstehe ich nicht. (https://github.com/HUSST-de/HUSST/issues/45) geht ja genau darum, Personal und Tarif getrennt zu versorgen. Der Unterschied zwischen Variante 2 und 3 ist: Haben wir am Ende zwei oder drei .xsd?
# Variante 2:
HUSST_Basisversorgungsdaten.xsd
HUSST_Versorgungsdaten.xsd (referenziert HUSST_Basisversorgungsdaten.xsd)
HUSST_Personaldaten.xsd (referenziert HUSST_Basisversorgungsdaten.xsd)
# Variante 3:
HUSST_Versorgungsdaten.xsd
HUSST_Personaldaten.xsd  (referenziert HUSST_Versorgungsdaten.xsd)

**Comment by AMCON-Gerst** [comment]
@horst-p-w-neubauer 
Also sollen bei Variante 3 im Root-Element nur die Elemente aus Versorungsdaten genutzt werden, die bei Variante 2 in Basisversorgungsdaten stehen.
Ich dachte man könnte im Root-Element der Personaldaten alle Elemente aus Versorungsdaten nutzen und daher eine Mischversorgung machen.

Unter den Umstängenfinde ich Variante 2 noch sinnvoller.

**Comment by horst-p-w-neubauer** [comment]
OK, dannn nochmal herzlichen Dank für alle Rückmeldungen. Das Ergebnis ist eindeutig: Variante 2 - Teilmodularisierung mit drei .xsd Dateien.

**Comment by horst-p-w-neubauer** [comment]
OK, dannn nochmal herzlichen Dank für alle Rückmeldungen. Das Ergebnis ist eindeutig: Variante 2 - Teilmodularisierung mit drei .xsd Dateien.
