### ISSUE TITLE
Versorgungsdaten OrtspunkteKA fehlende ID

### ISSUE THREAD

**Issue by BenedictSchwenker** [HUSST-de/HUSST#49]
Der OrtspunkteKA_Type besitzt momentan nur eine ID_Ortspunkt, welche mit der Zeitraum ID den PK bildet.
Um die Tabelle sinnvoll zu nutzen, bräuchte man aber zusätzlich eine ID_OrtspunktKA, welche mit der Zeitraum ID den PK bildet.
Die ID_Ortspunkt sollte nicht im PK auftauchen.

**Comment by horst-p-w-neubauer** [comment]
@HUSST-de/arbeitsgruppe 
könnt ihr euch bitte den Arbeitsstand anschauen und mir Rückmeldung geben?
Ich habe den Eindruck den OrtspunkteKA täte jetzt auch ein unique key gut - analog OrtspunkteTG

so sieht der bei OrtspunkteTG aus
``` xml
        <api:uniquekey name="Uix_OrtspunkteTG">
          <api:field name="ID_Ortspunkt"/>
          <api:field name="ID_Tarifgebiet"/>
          <api:field name="ID_Zeitraum"/>
        </api:uniquekey>
```
so stelle ich mir den bei bei OrtspunkteKA vor
``` Xml
        <api:uniquekey name="Uix_OrtspunkteKA">
          <api:field name="ID_Ortspunkt"/>
          <api:field name="KA_OrtOrgID"/>
          <api:field name="ID_Zeitraum"/>
        </api:uniquekey>
```

**Comment by BenedictSchwenker** [comment]
@horst-p-w-neubauer Ja den unique key finden wir auch sinnvoll.
