### ISSUE TITLE
Strecke_Type: SortOrder ergänzen

### ISSUE THREAD

**Issue by raoulvr** [HUSST-de/HUSST#58]
Strecken sollten wie [Relationen](https://github.com/HUSST-de/HUSST/blob/13c5a03658caedee962376adb05496dcd1d37ff4/Version%203/3.4.1/HUSST_Versorgungsdaten_3_4_1.xsd#L1327C25-L1327C40) über eine `SortOrder` sortierbar sein.

Zwischenfrage: Ist es gewollt, dass `Strecke_Type` im Singular ist?

https://github.com/HUSST-de/HUSST/blob/13c5a03658caedee962376adb05496dcd1d37ff4/Version%203/3.4.1/HUSST_Versorgungsdaten_3_4_1.xsd#L5577

**Comment by horst-p-w-neubauer** [comment]
Husst-AG vom 2024-03-08 - wird übernommen
