### ISSUE TITLE
DefStreckencodetyp_Type: HAST in AST umbenennen

### ISSUE THREAD

**Issue by raoulvr** [HUSST-de/HUSST#59]
`DefStreckencodetyp_Type `definiert HAST, NAST und NE-Haltepunkte, aber AST wäre eigentlich besser als HAST, weil HAST AST ist, AST aber nicht unbedingt HAST.

https://github.com/HUSST-de/HUSST/blob/13c5a03658caedee962376adb05496dcd1d37ff4/Version%203/3.4.1/HUSST_Versorgungsdaten_3_4_1.xsd#L5546

**Comment by horst-p-w-neubauer** [comment]
Husst-AG vom 2024-03-08 - wird übernommen
