### ISSUE TITLE
ID_DynAttributDef: xs:integer durch husstDV:INT4 ersetzen

### ISSUE THREAD

**Issue by raoulvr** [HUSST-de/HUSST#60]
`ID_DynAttributDef` nutzt als einziges Element `xs:integer`, sollte aber eigentlich auch `husstDV:INT4` verwenden.

⚠️ Das ist evtl. ein Breaking Change, weil es den effektiven Datentyp von `int` auf `uint` ändert.

https://github.com/HUSST-de/HUSST/blob/13c5a03658caedee962376adb05496dcd1d37ff4/Version%203/3.4.1/HUSST_Versorgungsdaten_3_4_1.xsd#L6044

**Comment by horst-p-w-neubauer** [comment]
Husst-AG vom 2024-03-08 - wird übernommen
